spring.application.name=ThesisBuddy

# ????? (????)
spring.datasource.url=jdbc:mysql://localhost:3306/thesis_selection_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

# Flyway ??
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=6
spring.flyway.locations=classpath:db/migration

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.example.thesisbuddy.entity
mybatis.configuration.map-underscore-to-camel-case=true
